### ISSUE TITLE
[BUG] Sprinting does not take hunger in v1.2.0

### ISSUE THREAD

**Issue by hypigler** [X-Niter/HungerIsStamina#1]
**In Detail, Explain the issue**
Sprint and it will take stamina.

**Steps to reproduce the behavior**
Sprint in-game.

**Expected behavior**
Take stamina while running.

**Screenshots**
If applicable
https://pastebin.com/VBYX9tvt
(not screenshot but yes)

**Plugin/Server versions**
Fill in what's applicable to you!
 - HungerIsStamina:  "1.2.0" 
 - MMOCore:  "1.8.0" 
 - MythicLib:  "1.1.3" 
 - PaperMc:  "VersionHere" 
 - Spigot:  "VersionHere" 
 - Bukkit:  "VersionHere" 
 - Purpur: "Purpur-1355 MC 1.17.1"

**Additional Comments**
Say more if you can or need to.

**Comment by X-Niter** [comment]
Are you using MMOCore Stamina placeholder in the action bar or ScoreBoard? 

If so, does the value change when you run, if no, then try swimming and see what happens.

If you're not using the placeholder, go ahead and add it somewhere "ActionBar" or scoreboard, then start running, keep running past 0 stamina and you should then begin to lose hunger. 

I originally meant to make stamina and hunger the exact same thing meaning your hunger bar becomes a simple stamina bar, however, I had some influence by others and ended up making a more complex system that drains stamina then drains the hunger.

If you're looking for the feature of the Hunger bar completely being the stamina, the "API" option for that will be introduced in the next release.

**Comment by hypigler** [comment]
I just realised i have written it about taking Stamina instead of the hunger bar, so sorry. Is it supposed to drain the hunger bar as of now?

**Comment by X-Niter** [comment]
> I just realised i have written it about taking Stamina instead of the hunger bar, so sorry. Is it supposed to drain the hunger bar as of now?

Keep sprinting past the point to which your stamina is gone, it will begin to take your character's hunger as consequence for over using your stamina reserves, causing your player the need to eat. 
This was set like this to create a more complex stamina system for users.

I'm working on the next update as we speak and in the update, I will be introducing a "SimpleStamina" config option which will turn the hunger bar into a Stamina bar.
As I'm working on that, you're more then welcomed to list all the ideas or expectations for it and I'll work to implement it.

**Comment by hypigler** [comment]
> > I just realised i have written it about taking Stamina instead of the hunger bar, so sorry. Is it supposed to drain the hunger bar as of now?
> 
> Keep sprinting past the point to which your stamina is gone, it will begin to take your character's hunger as consequence for over using your stamina reserves, causing your player the need to eat.
> This was set like this to create a more complex stamina system for users.
> 
> I'm working on the next update as we speak and in the update, I will be introducing a "SimpleStamina" config option which will turn the hunger bar into a Stamina bar.
> As I'm working on that, you're more then welcomed to list all the ideas or expectations for it and I'll work to implement it.

Oh Cool, i have an idea for the "SimpleStamina" option, which is basically mythiclib's health scaling, but for the hunger bar instead.

**Comment by X-Niter** [comment]
> > > I just realised i have written it about taking Stamina instead of the hunger bar, so sorry. Is it supposed to drain the hunger bar as of now?
> > 
> > 
> > Keep sprinting past the point to which your stamina is gone, it will begin to take your character's hunger as consequence for over using your stamina reserves, causing your player the need to eat.
> > This was set like this to create a more complex stamina system for users.
> > I'm working on the next update as we speak and in the update, I will be introducing a "SimpleStamina" config option which will turn the hunger bar into a Stamina bar.
> > As I'm working on that, you're more then welcomed to list all the ideas or expectations for it and I'll work to implement it.
> 
> Oh Cool, i have an idea for the "SimpleStamina" option, which is basically mythiclib's health scaling, but for the hunger bar instead.

Awesome! I got your message in discord so we can continue talking over on that, if you think this issue needs to stay here you can leave it open until the SimpleStamina API comes in. Or you can close it, up to you. :)
