### ISSUE TITLE
[BUG] SimpleStamina: Hunger is unable to regen when at 3 Whole Food Bars

### ISSUE THREAD

**Issue by hypigler** [X-Niter/HungerIsStamina#2]
**In Detail, Explain the issue**
Hunger is unable to regenerate when at 3 Whole Food bars (Sprinting Disabled) when using the simple stamina option, does hunger bar update only on sprinting? It will not be able to update if the player is unable to sprint.

**Steps to reproduce the behavior**
Reduce to 3 Whole Food Bars and your hunger is unable to by in sync with your stamina.

**Expected behavior**
Hunger to regenerate to be same with your stamina amount.

**Screenshots, logs, pastbins, gifs, videos, etc**
If applicable

**Plugin/Server versions**
Fill in what's applicable to you!

 - HungerIsStamina: "2.0" 
 - MMOCore: "1.8.0" 
 - MythicLib: "1.1.3" 
 - PaperMc: "VersionHere" 
 - Spigot: "VersionHere" 
 - Bukkit: "VersionHere" 
 - Purpur: "Purpur-1377 MC 1.17.1" 

**Additional Comments**
Say more if you can or need to.
no

**Comment by X-Niter** [comment]
You're correct, thank you for letting me know of this bug. 
I was able to re-produce this my self and it is true that when your stamina is regenerating, your hunger is not matching.
I'll be uploading the patch to fix this in the next few minutes!
![image](https://user-images.githubusercontent.com/30506033/132596863-0dc64570-9437-4322-beac-0e3222c1e360.png)
