### ISSUE TITLE
negative hunger

### ISSUE THREAD

**Issue by espen96** [X-Niter/HungerIsStamina#3]
it appears that hunger can go into the negatives if you try to run when both stamina and hunger is depleted.

**Comment by X-Niter** [comment]
Ah I see, I gotchu, I'll stop that from happening.

**Comment by X-Niter** [comment]
Thank you :)

**Comment by X-Niter** [comment]
Been a while on this, last few runs were succesful with out issues of this. 
I can only assume this is good to go.
