### ISSUE TITLE
[SUGGESTION] Deactivate world

### ISSUE THREAD

**Issue by Tylwen** [X-Niter/HungerIsStamina#4]
Add the possibility to deactivate the loss of stamania in a world (like a spawn or lobby)

**Comment by X-Niter** [comment]
Great idea, sorry for the delay got's lots on the plate, I've put it onto the project TODO board in IDE, I'll work on it when I get it opened up. 
Currently my IDE needs rebuilt due to windows crashing and needing re-installed. 
Sorry if the feature comes late.
