### ISSUE TITLE
[BUG] Maybe an error of Utilities

### ISSUE THREAD

**Issue by YKDZ** [X-Niter/HungerIsStamina#5]
**In Detail, Explain the issue**
Just a WARN when using plugin.

**Steps to reproduce the behavior**
install it and find error

**Screenshots, logs, pastbins, gifs, videos, etc**
https://mcpaste.com/47e6b83cfd620df2939c59fd8fc76686

**Plugin/Server versions**

 - HungerIsStamina: "1.3.0" 
 - MMOCore: "1.10.2" 
 - MythicLib: "1.4.1" 
 - Purpur: "purpur-1.19.2-1771"

**Comment by X-Niter** [comment]
Thanks @YKDZ , I know exactly what is wrong.
