### ISSUE TITLE
BROKEN PLACEHOLDER?

### ISSUE THREAD

**Issue by MaxHunko** [X-Niter/HungerIsStamina#6]
PLaceholders doesnt work

**Comment by MaxHunko** [comment]
discord link doesnt work. Write me in PM pls
Gordon_Ramsay | Максим#9463

**Comment by X-Niter** [comment]
Hey @MaxHunko 
The Discord link is fixed, in addition to that, what exact version of spigot/paper and this plugin are you using? 
Currently an update is in work for 1.20 build of MMO over at #8

**Comment by X-Niter** [comment]
@MaxHunko 
This should be resolved, if you find any issues, just come on back and let me know, thank you!
