### ISSUE TITLE
1.20 UPDATE

### ISSUE THREAD

**Issue by Xorbah** [X-Niter/HungerIsStamina#8]
**What's your question?**
I'd like to know if this will get updated to be compatible with the latest MMOCore/Items builds. The current build for Hunger Is Stamina repeatedly spits errors on the console. Has it been abandoned?

**Comment by X-Niter** [comment]
> 

@Xorbah 
I have been out of location from my desktop for some time now as I have been working on some IRL stability.
But to answer your question now that I am coming back, I will be updating it indeed!!

**Comment by LufuEZ** [comment]
Hey bro! It would really be great if you updated this resource to the new versions of MMO. I found it an incredibly fantastic addon. I have seen that the intention you have is to update it. Could you give us an approximate date of when you would have the resource ready? If you need a hand with something, I'll leave you my discord: lufu_

**Comment by wanderedwarlock** [comment]
@X-Niter Hey man! I'm so glad to hear you're getting back to this! Any progress? I tried to join your discord links to try and follow along but looks like invite links don't work anymore. I'm really looking forward to having a fleshed out stamina system where mmocore specifically lacks by default

**Comment by X-Niter** [comment]
Hey y'all, Need some alpha testing done to make sure what's getting published is as polished as possible.
Unzip the attached zip file and you'll have the plugin to test for MMO 1.20 builds.

Please report back on this issue thread, thank you!

[HungerIsStamina-2.2.0.zip](https://github.com/X-Niter/HungerIsStamina/files/12364288/HungerIsStamina-2.2.0.zip)

**Comment by X-Niter** [comment]
@LufuEZ  @wanderedwarlock @Xorbah 
I am closing this issue as it should work on latest versions, any bugs continuing from there I will work to resolve. 
It is people like you that keep me doing this, my reward is y'alls enjoyment, so thank you!
